micronaut:
  application:
    name: demo
  multitenancy:
    tenantresolver:
      httpheader:
        header-name: tenantId
        enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:h2:mem:devDbAlpha
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: NONE
    dialect: H2
  beta:
    url: jdbc:h2:mem:devDbBeta
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: NONE
    dialect: H2
jpa:
  default:
    packages-to-scan:
      - 'com.example.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase_changelog.xml'
    beta:
      change-log: 'classpath:db/liquibase_changelog.xml'